// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"
import TextareaAutogrow from 'stimulus-textarea-autogrow'
import DictionariesController from "./dictionaries_controller"
import QuizzController from "./quizz_controller"

application.register("dictionaries", DictionariesController)
application.register("quizz", QuizzController)
application.register('textarea-autogrow', TextareaAutogrow)